---
- name: restart ssh service - Debian
  ansible.builtin.systemd:
    state: restarted
    name: ssh
    
- name: restart ssh service - RedHat
  ansible.builtin.systemd:
    state: restarted
    name: sshd